services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "22:22"
    environment:
      - TZ=Asia/Bangkok
      - HOME=/var/jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - ./entrypoint.sh:/entrypoint.sh
      - ./.env:/etc/environment # Mount the .env file to the container
      - $PWD/Makefile:/home/jenkins/Makefile
    networks:
      - net
    user: root # This line ensures the script is run as root
    entrypoint: ["/bin/bash", "/entrypoint.sh"] # Start SSH and Jenkins
  remote_host:
    container_name: remote_host
    image: remote-host
    hostname: remote_host
    build:
      context: centos7
    networks:
      - net
    volumes:
      - $PWD/minio.sh:/tmp/script.sh
  db_host:
    container_name: db
    image: mysql:5.7
    hostname: db_host
    env_file:
      - .env
    volumes:
      - "$PWD/data:/var/lib/mysql"
    networks:
      - net
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000" # S3 API
      - "9090:9090" # Web UI
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always
    networks:
      - net

volumes:
  jenkins_home:
  minio_data:

networks:
  net:
